### ISSUE TITLE
Path config do not work as aspected

### ISSUE THREAD

**Issue by clausmuus** [letorbi/tarp.require#21]
A path config like
`<script>var TarpConfig = { require: { paths: "./lib/"} };</script>`
do not work in the latest version. Now it's necessary to write
`<script>var TarpConfig = { require: { paths: [(new URL("./lib/external/", location.href)).href] } };</script>`
Otherwise I get the message:
`TypeError: . is not a valid URL.`

**Comment by letorbi** [comment]
Thanks for reporting. Should be fixed with c85112d4bba111f6a47d6aa6fc178b69e517f072. Please reopen the issue if not.
