### ISSUE TITLE
Async preload do not use the correct path

### ISSUE THREAD

**Issue by clausmuus** [letorbi/tarp.require#22]
If I require a script async, then all require in this script, that do not use a relative path will do not use the configured path for preload. e.g.:
/index.html contains:
`Tarp.require('./index', true);`
index.js contains:
`require('my_mod');`
This will load the /index.js and than try to load the /my_mod.js. But correct would be to load the /node_modules/my_mod.js.
Later if the my_mod will be used, the correct my_mod will be loaded.

**Comment by letorbi** [comment]
Oh man, sorry for all the hassle :( Thx for reporting - I'm on it...

**Comment by letorbi** [comment]
Commit 42fe894140ba6641961553a8aa82a595ab33dbf9 should fix the problem. Please check out the current master-branch to verify whether issue is solved or not. Just reopen the issue if not.

**Comment by clausmuus** [comment]
Thank you, it works fine now :)
