### ISSUE TITLE
ignore of out-commented requires

### ISSUE THREAD

**Issue by clausmuus** [letorbi/tarp.require#23]
It would be grate, if it will be possible that the require preloader will ignore out-commented require calls.

**Comment by letorbi** [comment]
Yeah, this is an annoying problem. I will solve it when I improve the parser. For now more critical issues have priority, but [I won't forget it](https://github.com/letorbi/tarp.require/blob/2c8080258c4b870a7418417231368c7842f03439/require.js#L81) ;)
