### ISSUE TITLE
Pre-loader does not see calls to require if there is a space before the '('

### ISSUE THREAD

**Issue by jeberger** [letorbi/tarp.require#24]
Given the following code in a module:

```javascript
let sub = require ("foo");
```

Submodule `foo` is not preloaded. This is apparently due to the space between `require` and `(`.

**Comment by letorbi** [comment]
Thx for reporting :)

The problem should be solved with commit 254677d4ff13147a727eb8f4eebf0110e06a294. Could you please check out the latest master-branch and confirm this? Just re-open the issue if it is not solved.

**Comment by jeberger** [comment]
The latest master branch works, thanks.
