### ISSUE TITLE
when i require from 'node_modules' module , it can't find

### ISSUE THREAD

**Issue by saxihuangxing** [letorbi/tarp.require#30]
when it 
const EventEmitter = require('events'); 
that trans to 
http://localhost:63342/janus-videoroom-api/node_modules/events.js
but in reallity it in 
http://localhost:63342/janus-videoroom-api/node_modules/event/events.js
,even other module it not event.js , it can be any *.js.

**Comment by letorbi** [comment]
This behaviour seems to be in line with [the way how Node.js loads modules](https://nodejs.org/api/modules.html).

You should be able to load */janus-videoroom-api/node_modules/event/events.js* with the following line:

```
const EventEmitter = require('events');
```

Does this solve your problem?

**Comment by letorbi** [comment]
This behaviour seems to be in line with [the way how Node.js loads modules](https://nodejs.org/api/modules.html).

You should be able to load */janus-videoroom-api/node_modules/event/events.js* with the following line:

```
const EventEmitter = require('events/events');
```

Does this solve your problem?

**Comment by saxihuangxing** [comment]
thanks you fro suggestion ! in the end , i used browerily and it worked fine .
